# Generated by Django 4.2.5 on 2024-03-23 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0035_customer_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referred_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_referred_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('email_verification_code', models.CharField(blank=True, max_length=100)),
                ('email_isverified', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('vendor_active_email', models.BooleanField(default=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=12)),
                ('cusstomer_image', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('user_datecreated', models.DateTimeField(auto_now_add=True)),
                ('user_dateupdated', models.DateTimeField(auto_now=True)),
                ('referred_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_referred_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
