# Generated by Django 4.2.5 on 2024-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_cart_product_sizes_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sizes',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_sizes',
            name='product_size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Double Extra Large')], default=None, max_length=4),
        ),
    ]
