# Generated by Django 4.2.5 on 2024-04-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_favourite_favourite_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite_items',
            old_name='favoutire_ins',
            new_name='favourite_ins',
        ),
    ]
