# Generated by Django 4.2.5 on 2024-04-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_products_average_rating_products_total_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='average_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
