# Generated by Django 4.2.5 on 2024-04-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_offers',
            name='offer_page',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='itmclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='store.category'),
        ),
    ]
