# Generated by Django 4.2.5 on 2024-05-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_upi_credit_cards_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='recently_viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='midcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=50, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('itmclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='category_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_image', models.ImageField(blank=True, null=True, upload_to='images/offer_images/')),
                ('offer_url', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_upadated', models.DateTimeField(auto_now=True)),
                ('offer_catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='itmmidclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.midcategory'),
        ),
    ]
