# Generated by Django 4.2.5 on 2024-05-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_recently_viewed_midcategory_category_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midcategory',
            name='midcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/'),
        ),
    ]
