# Generated by Django 4.2.5 on 2024-05-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_category_offer_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
