# Generated by Django 4.2.5 on 2024-05-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_cartitems_count_cartitems_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='count',
            new_name='cart_count',
        ),
    ]
