# Generated by Django 4.2.5 on 2024-05-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_rename_count_cartitems_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='itmmidclass',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.midcategory'),
        ),
    ]
