from django.contrib import admin
from .models import *

admin.site.register(customer)
admin.site.register(buyer)
admin.site.register(products)
admin.site.register(orders)
admin.site.register(favourite)
admin.site.register(favourite_items)
admin.site.register(Cart)
admin.site.register(cartItems)
admin.site.register(address)
admin.site.register(category)
admin.site.register(subcategory)
admin.site.register(product_variants)
admin.site.register(product_sizes)
admin.site.register(product_metas)
admin.site.register(product_images)
admin.site.register(reviews)
admin.site.register(home_offers)
admin.site.register(discount)
admin.site.register(discount_type)
admin.site.register(LastLogin)
admin.site.register(order_invoices)
admin.site.register(midcategory)
admin.site.register(category_offer)
admin.site.register(recently_viewed)
